//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultScope
{
    using SiaqodbSyncProvider;
    using Sqo;


    public partial class Status : SiaqodbOfflineEntity
    {

        [Sqo.Attributes.Index()]
        private int _ID;

        private string _Name;

        [Sqo.Attributes.UseVariable("_ID")]
        [Microsoft.Synchronization.ClientServices.Key()]
        public int ID
        {
            get
            {
                return _ID;
            }
            set
            {
                _ID = value;
            }
        }

        [Sqo.Attributes.UseVariable("_Name")]
        public string Name
        {
            get
            {
                return _Name;
            }
            set
            {
                _Name = value;
            }
        }
    }

    public partial class Priority : SiaqodbOfflineEntity
    {

        [Sqo.Attributes.Index()]
        private int _ID;

        private string _Name;

        [Sqo.Attributes.UseVariable("_ID")]
        [Microsoft.Synchronization.ClientServices.Key()]
        public int ID
        {
            get
            {
                return _ID;
            }
            set
            {
                _ID = value;
            }
        }

        [Sqo.Attributes.UseVariable("_Name")]
        public string Name
        {
            get
            {
                return _Name;
            }
            set
            {
                _Name = value;
            }
        }
    }

    public partial class List : SiaqodbOfflineEntity
    {

        [Sqo.Attributes.Index()]
        private System.Guid _ID;

        private string _Name;

        private string _Description;

        private System.Guid _UserID;

        private System.DateTime _CreatedDate;

        [Sqo.Attributes.UseVariable("_ID")]
        [Microsoft.Synchronization.ClientServices.Key()]
        public System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                _ID = value;
            }
        }

        [Sqo.Attributes.UseVariable("_Name")]
        public string Name
        {
            get
            {
                return _Name;
            }
            set
            {
                _Name = value;
            }
        }

        [Sqo.Attributes.UseVariable("_Description")]
        public string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }

        [Sqo.Attributes.UseVariable("_UserID")]
        public System.Guid UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                _UserID = value;
            }
        }

        [Sqo.Attributes.UseVariable("_CreatedDate")]
        public System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                _CreatedDate = value;
            }
        }
    }

    public partial class TagItemMapping : SiaqodbOfflineEntity
    {

        [Sqo.Attributes.Index()]
        private int _TagID;

        [Sqo.Attributes.Index()]
        private System.Guid _ItemID;

        [Sqo.Attributes.Index()]
        private System.Guid _UserID;

        [Sqo.Attributes.UseVariable("_TagID")]
        [Microsoft.Synchronization.ClientServices.Key()]
        public int TagID
        {
            get
            {
                return _TagID;
            }
            set
            {
                _TagID = value;
            }
        }

        [Sqo.Attributes.UseVariable("_ItemID")]
        [Microsoft.Synchronization.ClientServices.Key()]
        public System.Guid ItemID
        {
            get
            {
                return _ItemID;
            }
            set
            {
                _ItemID = value;
            }
        }

        [Sqo.Attributes.UseVariable("_UserID")]
        [Microsoft.Synchronization.ClientServices.Key()]
        public System.Guid UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                _UserID = value;
            }
        }
    }

    public partial class Item : SiaqodbOfflineEntity
    {

        [Sqo.Attributes.Index()]
        private System.Guid _ID;

        private System.Guid _ListID;

        private System.Guid _UserID;

        private string _Name;

        private string _Description;

        private System.Nullable<int> _Priority;

        private System.Nullable<int> _Status;

        private System.Nullable<System.DateTime> _StartDate;

        private System.Nullable<System.DateTime> _EndDate;

        [Sqo.Attributes.UseVariable("_ID")]
        [Microsoft.Synchronization.ClientServices.Key()]
        public System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                _ID = value;
            }
        }

        [Sqo.Attributes.UseVariable("_ListID")]
        public System.Guid ListID
        {
            get
            {
                return _ListID;
            }
            set
            {
                _ListID = value;
            }
        }

        [Sqo.Attributes.UseVariable("_UserID")]
        public System.Guid UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                _UserID = value;
            }
        }

        [Sqo.Attributes.UseVariable("_Name")]
        public string Name
        {
            get
            {
                return _Name;
            }
            set
            {
                _Name = value;
            }
        }

        [Sqo.Attributes.UseVariable("_Description")]
        public string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }

        [Sqo.Attributes.UseVariable("_Priority")]
        public System.Nullable<int> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                _Priority = value;
            }
        }

        [Sqo.Attributes.UseVariable("_Status")]
        public System.Nullable<int> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                _Status = value;
            }
        }

        [Sqo.Attributes.UseVariable("_StartDate")]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                _StartDate = value;
            }
        }

        [Sqo.Attributes.UseVariable("_EndDate")]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                _EndDate = value;
            }
        }
    }

    public partial class User : SiaqodbOfflineEntity
    {

        [Sqo.Attributes.Index()]
        private System.Guid _ID;

        private string _Name;

        [Sqo.Attributes.UseVariable("_ID")]
        [Microsoft.Synchronization.ClientServices.Key()]
        public System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                _ID = value;
            }
        }

        [Sqo.Attributes.UseVariable("_Name")]
        public string Name
        {
            get
            {
                return _Name;
            }
            set
            {
                _Name = value;
            }
        }
    }

    public partial class Tag : SiaqodbOfflineEntity
    {

        [Sqo.Attributes.Index()]
        private int _ID;

        private string _Name;

        [Sqo.Attributes.UseVariable("_ID")]
        [Microsoft.Synchronization.ClientServices.Key()]
        public int ID
        {
            get
            {
                return _ID;
            }
            set
            {
                _ID = value;
            }
        }

        [Sqo.Attributes.UseVariable("_Name")]
        public string Name
        {
            get
            {
                return _Name;
            }
            set
            {
                _Name = value;
            }
        }
    }
}
